name: buildcache debug

on:
  workflow_dispatch:

jobs:
  debug:
    runs-on: macos-latest
    steps:
    - name: install buildcache
      uses: mikehardy/buildcache-action@v1
      with:
        cache_key: mac-bcache-debug

    - name: test installation
      run: which buildcache
