name: Validation

on:
  push

env:
  BUILD_TYPE: Release
  PLUGINVAL_LEVEL: 6    # Strictness level for pluginval validation

# Jobs run in parallel by default
jobs:
  build_and_validate:
    name: Build and validate on ${{ matrix.config.name }}
  
    runs-on: ${{ matrix.config.os }}
    
    strategy:
      # Don't cancel all in-progress jobs if any matrix job fails:
      fail-fast: false
      # Define a matrix of job configurations:
      matrix:
        config:
        - {
            name: 'MacOS Latest',
            os: macos-latest,
            gen: 'Xcode',
            # Use Xcode generator for faster builds. Enable building a universal binary.
            cmake_config_flags: "-G Xcode -D CMAKE_OSX_ARCHITECTURES=arm64\\;x86_64",
            # Force Xcode to use compilers from the PATH to enable buildcache
            cmake_build_flags: "-- CC=clang CPLUSPLUS=clang++ LD=clang LDPLUSPLUS=clang++ -quiet"
          }
        - {
            name: 'Windows Latest',
            os: windows-latest,
            gen: 'MSVC'
          }

    # Steps run in sequence. Each step runs in its own process in the runner environment and has access to the workspace and filesystem
    # NB! Because steps run in their own process, changes to environment variables are not preserved between steps
    steps:
    
    - name: Checkout code 
      uses: actions/checkout@v2

    # Use the buildcache compiler cache to speed up builds
    # Note: currently we are not configuring buildcache to work on Windows
    # Details: https://github.com/mbitsnbites/buildcache/blob/master/doc/usage.md#using-with-visual-studio--msbuild
    - name: Enable buildcache
      if: runner.os != 'Windows'
      uses: mikehardy/buildcache-action@v1
      with:
        cache_key: ${{ runner.os }}-${{ env.BUILD_TYPE }}

    # Set up the dependency cache to be updated for every new commit
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: Libs
        key: libs-${{ runner.os }}-${{ matrix.config.gen }}-${{ github.sha }}
        restore-keys: libs-${{ runner.os }}-${{ matrix.config.gen }}-

    - name: Configure CMake
      # Configure CMake in a 'Build' subdirectory.
      run: cmake -B Build ${{ matrix.config.cmake_config_flags }}

    - name: Build
      # Build the project with the given configuration.
      run: cmake --build Build --config ${{ env.BUILD_TYPE }} ${{ matrix.config.cmake_build_flags }}

    - name: Validate (Mac)
      if: runner.os == 'MacOS'
      working-directory: Build
      env:
        STRICTNESS_LEVEL: ${{ env.PLUGINVAL_LEVEL }}
        #VALIDATE_IN_PROCESS: true
      run: |
        curl -LsS "https://github.com/Tracktion/pluginval/releases/latest/download/pluginval_macOS.zip" -o pluginval.zip
        unzip -q pluginval
        pluginval.app/Contents/MacOS/pluginval --validate-in-process --validate "PluginTemplate_artefacts/Release/VST3/Plugin Template.vst3"
